services:
  backend:
    build: ./api
    ports:
      - "5000:8080"
    environment:
      - FLASK_ENV=production
    env_file:
      - ./api/.env
    volumes:
      - ./models:/app/models

  frontend:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
